# Generated by Django 6.0.3 on 2026-03-24 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waf_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='alert',
            new_name='waf_core_al_created_755561_idx',
            old_name='waf_core_al_created_idx',
        ),
        migrations.RenameIndex(
            model_name='detectedattack',
            new_name='waf_core_de_timesta_30ae19_idx',
            old_name='waf_core_de_timesta_idx',
        ),
        migrations.RenameIndex(
            model_name='httprequest',
            new_name='waf_core_ht_timesta_0856c4_idx',
            old_name='waf_core_ht_timesta_idx',
        ),
        migrations.RenameIndex(
            model_name='httprequest',
            new_name='waf_core_ht_client__7c10a2_idx',
            old_name='waf_core_ht_client__idx',
        ),
        migrations.AlterField(
            model_name='alert',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
